### ISSUE TITLE
Why XFCE? seems like a waste of time to me

### ISSUE THREAD

**Issue by enigma0x7** [postmarketOS/xfce4-phone#3]
With better desktop options available now like Budgie Desktop why would you waste time on XFCE development?

Personally, I am working on getting Alpine Linux and Budgie Desktop working together for my Desktop computers. I will probably try to do the same on an old android device if possible. I really want to see postmarketOS succeed but I think you might need a better name.

With the jaw-dropping lack of security on any smartphone, it is baffling why anyone would use them for more than toys. I hope postmarket changes all that but you should give it a name that embraces security.

Why not something like EnigmaOS after the Usenix Enigma Security Conference which is dedicated to most of the problems postmarketOS intends to solve. With a name like that you will get a lot more attention and hence more contributors.

Not trying to be a Debbie downer, I just want this project to succeed where others have failed, you already have the right idea by basing it off of Alpine Linux best solution I have seen so far.

**Comment by ollieparanoid** [comment]
> With better desktop options available now like Budgie Desktop why would you waste time on XFCE development?

That is a matter of taste. Some people like to use XFCE4, and that's why it was packaged. People are working on a few other different UIs actually, such as Plasma Mobile, LuneOS, Hildon, Gnome. Users will be able to choose the desktop they want to use, just like with a desktop Linux distribution. See also: ["Why we evolve in many directions"](https://postmarketos.org/blog/2017/09/03/100-days-of-postmarketos/#why-we-evolve-in-many-directions).

> Personally, I am working on getting Alpine Linux and Budgie Desktop working together for my Desktop computers. I will probably try to do the same on an old android device if possible.

If you can make it work for Alpine, it is pretty easy to make it work for postmarketOS as well. Just create a `postmarketos-ui-budgie` package, that pre-configures the desktop (look at the other `postmarketos-ui-*` aports for inspiration in the [pmbootstrap repo](https://github.com/postmarketOS/pmbootstrap)) and you're done.

> I really want to see postmarketOS succeed but I think you might need a better name.

> With a name like [EnigmaOS] you will get a lot more attention and hence more contributors.

That is a matter of taste as well, [here](https://news.ycombinator.com/item?id=15160993) is a discussion that has some pros (e.g. name says what it is about and is not too generic) and cons. I like the name personally, and by now it stands for all the great work we have done as a community so I don't think we'll change it any time soon. Our strategy for getting new contibutors are the bigger blog posts we do when the project's days counter reaches a round number and that worked out pretty well so far.

Thanks for your feedback, I hope all your questions are answered. Let us know if you have further questions and maybe consider contributing something to the project (we try to make development as enjoyable as possible, skim through the [porting guide](https://wiki.postmarketos.org/wiki/Porting_to_a_new_device) for a first impression).

**Comment by enigma0x7** [comment]
Yes it does, thats good to know about multiple desktops being supported. I mistakenly thought it would be more like a typical phone with what you see is what you get.

As far as the name goes, I understand your sentiment but reality is the name is very DEV minded, I do not ever see it becoming a mainstream name for the very reasons facebook financers forced Mark Zuckerberg to change the name from "Thefacebook.com" to just "facebook".

I feel that civil liberties should not be a luxury of the few that are educated, unfortunately like any product the challenge of education is ultimately the downfall of the product. It is the same reason Shark Tank investors do not invest in products which require educating the customer.

Instead, people are influenced by short catchy names with quick excerpts of why a product is so great because like Steve Jobs as much as a despise him was right, the majority is sheep and everything needs to be dumbed down.

Examples:
IOS
Android
Facebook
Google
Firefox
Chrome
EOS <--- short for EnigmaOS

I am not saying jump on the enigmaOS bandwagon, pick any branded name. I am just using it as an example to say hit the ground running with the knowledge the big players use to be successful. Branding is everything especially in an industry as cutthroat as cellular. Most people do not even understand why they need something like postmarketOS so the odds are already against its success, In my opinion, a good strong branded name is your only chance with the exception of a handful of geeks who will use it because they know why they need it. Otherwise, I sadly feel it will just end up like any of the other linux phone platforms.

**Comment by ollieparanoid** [comment]
> the name is very DEV minded, I do not ever see it becoming a mainstream name

That is perfect for the situation we have right now. postmarketOS can't even do phone calls at this stage, so why bother reaching out to non-developers?

My opinion is, that changing the name is only worth it if pmOS is ready for being a daily-driver and we notice that the current name is holding us back somehow. But it's not like we're fighting over market shares with Apple and Google any time soon 😉 

(With that being said, we make decisions together in the community, so it's the whole community's opinion that counts.)

**Comment by enigma0x7** [comment]
All great points and yes and I understand that it is very DEV only at the moment, I was just telling someone about it during thanksgiving dinner and said it will probably be a few years until it can compete.

I do feel that brand recognition starts even in the earlier days, I have products that I come across all the time in their early days which are not quite there but are promising. Later I check back wether its in 6 months or a year. But honestly, if postmarketOS was one of those that I was just going to check back in on then I would never remember the name to do so.

I remember the early days of EMC before anyone ever knew who they were and long before Dell ever bought them out. If I remember correctly the stocks were worth pennies on the dollar back then. Yet even know I never used their products the name stuck in my head for a couple of decades.
